# Generated by Django 4.2.16 on 2026-07-30 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_curlparserecord_parsed_result_historyentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curlparserecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curl_parse_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='curlparserecord',
            index=models.Index(fields=['owner', '-created_at'], name='api_curlpar_owner_i_33017c_idx'),
        ),
    ]
