# Generated by Django 4.2.16 on 2026-07-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_curlparserecord_owner_and_more'),
    ]

    def dedupe_active_envs(apps, schema_editor):
        # Safety net: if a prior race left multiple active envs for an owner,
        # keep only the most-recently-updated one before the unique constraint
        # is enforced. No-op when data is already clean.
        Environment = apps.get_model('api', 'Environment')
        owners = list(
            Environment.objects.filter(is_active=True)
            .values_list('owner', flat=True)
            .distinct()
        )
        for owner in owners:
            active = Environment.objects.filter(owner=owner, is_active=True).order_by('-updated_at')
            keep = active.first()
            if keep is not None:
                active.exclude(id=keep.id).update(is_active=False)

    def _reverse_noop(apps, schema_editor):  # pragma: no cover - irreversible data fix
        pass

    operations = [
        migrations.RunPython(dedupe_active_envs, _reverse_noop),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner',), name='uniq_active_env_per_owner'),
        ),
    ]
