# Generated by Django 4.2.16 on 2026-07-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_environment_uniq_active_env_per_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurlParseRecord',
        ),
    ]
