# Generated by Django 4.2.30 on 2026-07-22 12:17

from django.db import migrations, models
import django.db.models.deletion


# ── Backfill project colors (ported from 0006_backfill_project_colors) ──
PROJECT_COLORS = [
    '#e53935', '#d81b60', '#8e24aa', '#5e35b1', '#3949ab',
    '#1e88e5', '#039be5', '#00acc1', '#00897b', '#43a047',
    '#7cb342', '#c0ca33', '#fdd835', '#ffb300', '#fb8c00',
    '#f4511e', '#ec407a', '#ab47bc', '#7e57c2', '#5c6bc0',
    '#42a5f5', '#29b6f6', '#26c6da', '#26a69a', '#66bb6a',
    '#9ccc65', '#d4e157', '#ffee58', '#ffca28', '#ffa726',
    '#ff7043', '#ff1744', '#aa00ff', '#6200ea',
    '#2962ff', '#0091ea', '#00b8d4', '#00bfa5', '#64dd17',
    '#aeea00', '#ffd600', '#ffab00', '#ff6d00',
]


def backfill_project_colors(apps, schema_editor):
    Project = apps.get_model('schedule', 'Project')
    projects = list(Project.objects.filter(color__in=['', '#10b981']))
    if not projects:
        return
    used = list(Project.objects.exclude(
        color__in=['', '#10b981']
    ).values_list('color', flat=True))
    usage = {c: used.count(c) for c in PROJECT_COLORS}
    for project in projects:
        color = min(PROJECT_COLORS, key=lambda c: usage.get(c, 0))
        project.color = color
        usage[color] = usage.get(color, 0) + 1
        project.save(update_fields=['color'])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    replaces = [('schedule', '0001_initial'), ('schedule', '0002_holiday'), ('schedule', '0003_alter_schedule_options_alter_schedule_person_and_more'), ('schedule', '0004_delete_holiday_remove_schedule_detail_and_more'), ('schedule', '0005_holiday'), ('schedule', '0006_backfill_project_colors'), ('schedule', '0007_schedule_assignee_schedule_role_requirement_and_more'), ('schedule', '0008_assignment_remove_schedule_project_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#10b981', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedule.project')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_off_day', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RunPython(
            code=backfill_project_colors,
            reverse_code=reverse_backfill,
        ),
        migrations.AddField(
            model_name='schedule',
            name='assignee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('RD', 'RD'), ('FE', 'FE'), ('QA', 'QA'), ('UI', 'UI'), ('PM', 'PM'), ('DevOps', 'DevOps')], max_length=50)),
                ('assignee', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedule.project'),
        ),
    ]
