# Generated by Django 4.2.30 on 2026-07-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_squashed_0008_assignment_remove_schedule_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignee',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='role',
            field=models.CharField(blank=True, choices=[('RD', 'RD'), ('FE', 'FE'), ('QA', 'QA'), ('UI', 'UI'), ('PM', 'PM'), ('DevOps', 'DevOps')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_project_name'),
        ),
    ]
