# Generated by Django 4.2.16 on 2026-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_remove_project_unique_project_name_assignment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
