# Generated by Django 4.2.16 on 2026-08-03 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this mock', max_length=200)),
                ('path', models.CharField(help_text='Mock path, e.g. api/users/&lt;user_id&gt;. Supports &lt;param&gt; placeholders.', max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('python_script', models.TextField(blank=True, default='', help_text='Python script — must define a handle(request) function that returns a dict with keys: status_code, headers, body.')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('enabled', models.BooleanField(default=True)),
                ('delay_ms', models.IntegerField(default=0, help_text='Simulated latency in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='mock_mocken_owner_i_e3b435_idx'), models.Index(fields=['owner', 'enabled'], name='mock_mocken_owner_i_241473_idx')],
                'unique_together': {('owner', 'path', 'method')},
            },
        ),
    ]
