# Generated by Django 4.2.16 on 2026-08-04 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mockendpoint',
            unique_together={('path', 'method')},
        ),
        migrations.AlterField(
            model_name='mockendpoint',
            name='delay_ms',
            field=models.IntegerField(default=0, help_text='Simulated latency in milliseconds (max 60s)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60000)]),
        ),
    ]
